[package]
name = "server_example"
version = "0.1.0"
authors = ["Edgar Adri√°n <adick.teddy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
